添加了 平行时空团队 契约链项目的介绍和部分源代码 （修改）
ParityAsia/hackathon-2021-summer pull request #42
Opened 2021-07-04 15:26 UTC by liusanchuan

...

2021-07-05 07:05 UTC, liusanchuan commented
添加了PPT

2021-07-05 10:03 UTC, jimmychu0807 commented
@liusanchuan 麻煩把根目錄裡的 `docs/img/*`, `docs/logo/*`, 及平行時空參賽項目介紹檔案 移到 `teams/23-平行時空/docs` 裡面。

2021-07-05 10:05 UTC, jimmychu0807 requested changes
看留言，根目录内容不能改。只能改自己团队目录里的内容。

2021-07-05 10:49 UTC, liusanchuan commented
已修改

2021-07-06 02:00 UTC, jimmychu0807 approved these changes

2021-07-06 02:06 UTC, merged